import { FileInfo } from "../component/FileInfo/FileInfo";
import { IFileUpload } from "../interfaces/IFileUpload";

export const data:Array<IFileUpload>=[ {fileId: '12345',
    fileName:'Text.xlsx',
    isUploaded:false,
    progress:40,
    isCanceled:false,
    isFailed:false,
    initialTime:new Date(),
    finalTime:new Date(),
    updateData:()=>null
},
{fileId: '12345',
    fileName:'Text.xlsx',
    isUploaded:false,
    progress:40,
    isCanceled:false,
    isFailed:false,
    initialTime:new Date(),
    finalTime:new Date(),
    updateData:()=>null
},
{fileId: '12345',
    fileName:'Text.xlsx',
    isUploaded:false,
    progress:40,
    isCanceled:false,
    isFailed:false,
    initialTime:new Date(),
    finalTime:new Date(),
    updateData:()=>null
},
{fileId: '12345',
    fileName:'Text.xlsx',
    isUploaded:false,
    progress:40,
    isCanceled:false,
    isFailed:false,
    initialTime:new Date(),
    finalTime:new Date(),
    updateData:()=>null
},
{fileId: '12345',
    fileName:'Text.xlsx',
    isUploaded:false,
    progress:40,
    isCanceled:false,
    isFailed:false,
    initialTime:new Date(),
    finalTime:new Date(),
    updateData:()=>null
},
{fileId: '12345',
    fileName:'Text.xlsx',
    isUploaded:false,
    progress:40,
    isCanceled:false,
    isFailed:false,
    initialTime:new Date(),
    finalTime:new Date(),
    updateData:()=>null
},
{fileId: '12345',
    fileName:'Text.xlsx',
    isUploaded:false,
    progress:40,
    isCanceled:false,
    isFailed:false,
    initialTime:new Date(),
    finalTime:new Date(),
    updateData:()=>null
},
{fileId: '12345',
    fileName:'Text.xlsx',
    isUploaded:false,
    progress:40,
    isCanceled:false,
    isFailed:false,
    initialTime:new Date(),
    finalTime:new Date(),
    updateData:()=>null
},
{fileId: '12345',
    fileName:'Text.xlsx',
    isUploaded:false,
    progress:40,
    isCanceled:false,
    isFailed:false,
    initialTime:new Date(),
    finalTime:new Date(),
    updateData:()=>null
},
{fileId: '12345',
    fileName:'Text.xlsx',
    isUploaded:false,
    progress:40,
    isCanceled:false,
    isFailed:false,
    initialTime:new Date(),
    finalTime:new Date(),
    updateData:()=>null
},
{fileId: '12345',
    fileName:'Text.xlsx',
    isUploaded:false,
    progress:40,
    isCanceled:false,
    isFailed:false,
    initialTime:new Date(),
    finalTime:new Date(),
    updateData:()=>null
},

    {fileId: '123456',
    fileName:'Sample.pdf',
    isUploaded:false,
    initialTime:new Date(),
    finalTime:new Date(),
    progress:30,
    isFailed:true,
    isCanceled:false,
    updateData:()=>null},
    {
        fileId: '123457',
    fileName:'Presentation.ppt',
    isUploaded:false,
    initialTime:new Date(),
    finalTime:new Date(),
    isFailed:false,

    progress:100,
    isCanceled:true,
    updateData:()=>null},{
        fileId: '123457',
    fileName:'Image.jpg',
    isUploaded:true,
    initialTime:new Date(),
    finalTime:new Date(),
    isFailed:false,

    progress:100,
    isCanceled:false,
    updateData:()=>null}]

    export const fileInfoArray:Array<FileInfo>=[]

